CREATE TABLE Sede(
  Nombre VARCHAR(25) NOT NULL,
  Codigo_Sede INTEGER NOT NULL,
  Rut INTEGER NOT NULL,
  Horario TIMESTAMP NOT NULL,
  Localidad VARCHAR(25) NOT NULL,
  Ciudad VARCHAR(25) NOT NULL,
  CONSTRAINT pcs PRIMARY KEY (Codigo_Sede)
);
